# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12qiL33chbwQIjd0C5Zq1ltR9q8gWujev
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# নমুনা ডেটা
data = {
    'text': ['Free lottery', 'Hi friend', 'Win money', 'Call me later'],
    'label': ['spam', 'ham', 'spam', 'ham']
}
df = pd.DataFrame(data)

# ট্রেনিং
cv = CountVectorizer()
X = cv.fit_transform(df['text'])
model = MultinomialNB()
model.fit(X, df['label'])

print("Model is ready!")

# একটি নতুন মেসেজ চেক করা
test_message = ["Congratulations! You won a free gift card. Click here to claim."]

# মেসেজটিকে সংখ্যায় রূপান্তর
test_vector = cv.transform(test_message)

# প্রেডিকশন দেখা
result = model.predict(test_vector)

print(f"মেসেজটি হলো: {result[0]}")

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# from sklearn.feature_extraction.text import CountVectorizer
# from sklearn.naive_bayes import MultinomialNB
# 
# st.title("Email Spam Detector")
# st.write("Enter a message to check if it's Spam or Not.")
# 
# # Simple Training Data
# data = {'text': ['Free money now', 'Hi, how are you?', 'Claim prize', 'Meeting at 10am'],
#         'label': ['spam', 'ham', 'spam', 'ham']}
# df = pd.DataFrame(data)
# 
# cv = CountVectorizer()
# X = cv.fit_transform(df['text'])
# model = MultinomialNB()
# model.fit(X, df['label'])
# 
# user_input = st.text_input("Message:")
# if st.button("Predict"):
#     if user_input:
#         vect = cv.transform([user_input]).toarray()
#         prediction = model.predict(vect)
#         st.success(f"This is a: {prediction[0].upper()}")
#     else:
#         st.warning("Please enter a message.")